apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-web
  namespace: iast-prod
  annotations:
    kubesphere.io/description: dongtai前端项目
  labels:
    app: dongtai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-web
  template:
    metadata:
      labels:
        app: dongtai-web
    spec:
      containers:
        - name: dongtai-web-container
          image: dongtai/dongtai-web:VERSION
          imagePullPolicy: Always
          env:
          - name: aliyun_logs_iast_server_project
            value: k8s-log-c541e7d8ffff2434a8b7b4fd7d8645d2a
          - name: aliyun_logs_iast_server
            value: stdout
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi