apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingzhi-web
  namespace: huoqi-prod
  annotations:
    kubesphere.io/description: lingzhi前端
  labels:
    app: lingzhi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lingzhi-web
  template:
    metadata:
      labels:
        app: lingzhi-web
    spec:
      containers:
        - name: lingzhi-web-container
          image: registry-vpc.cn-beijing.aliyuncs.com/secnium/lingzhi-web:VERSION
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
      imagePullSecrets:
        - name: huoqi-regsecret-huoqi-prod
