name: Deploy DongTai-Web to AWS

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  Deploy-To-Test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: start-build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建开始\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}
      
      - name: test and build
        run: |
          npm ci
          npm test
          npm run build --if-present

      #- name: Build and push
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    push: true
      #    tags: |
      #      registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:latest
      #      registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:1.0.${{github.run_number}}
      - name: Build
        run: |
          docker build -t registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:latest .
          docker tag registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:latest  registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:1.0.${{github.run_number}}
          
      - name: push
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 300
          max_attempts: 10
          #retry_on: timeout
          command: |
            docker push registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:latest
            docker push registry.cn-beijing.aliyuncs.com/secnium/iast-saas-web-test:1.0.${{github.run_number}}


      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find deploy/deploy-eks-iast-saas-web-test.yml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}/g' {} \;
            ls deploy/deploy-eks-iast-saas-web-test.yml | xargs -I {} kubectl apply -f {}
      
      - name: finish build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建完成\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'
