name: Deploy DongTai-Web to Release

on:
  push:
    branches: [ "release-*" ]
  pull_request:
    branches: [ "release-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: start-build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建开始\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

      - name: checkout
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DONGTAI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DONGTAI_DOCKERHUB_TOKEN }}

      - name: Login to AliyunRegistry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

      - name: test and build
        run: |
          npm ci
          npm test
          npm run build --if-present

      - name: test
        run: |
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF##*/} | awk -F'-' '{print $2}'

      - id: release
        run: |
          VERSION=`echo ${GITHUB_REF##*/} | awk -F'-' '{print $2}'` && echo "::set-output name=version::$VERSION"

      - name: Generate version file
        run: |
          cd ${{ github.workspace }} && \
          echo "${{ github.event.repository.name }},version,${{ steps.release.outputs.version }}" >> dist/version.txt && \
          echo "${{ github.event.repository.name }},commit_hash,${GITHUB_SHA}" >> dist/version.txt && \
          cat dist/version.txt \

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

      - name: Upload version file to oss
        run: |
          ossutil cp -rf dist/version.txt oss://huoqi-public/iast/release-version/${{ github.event.repository.name }}/${{ steps.release.outputs.version }}/version.txt

      - name: Merge all version file
        run: |
          echo "DongTai,version,${{ steps.release.outputs.version }}" > dist/version.txt
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-web/${{ steps.release.outputs.version }}/version.txt DongTai-web.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-webapi/${{ steps.release.outputs.version }}/version.txt DongTai-webapi.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-openapi/${{ steps.release.outputs.version }}/version.txt DongTai-openapi.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-engine/${{ steps.release.outputs.version }}/version.txt DongTai-engine.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-agent-python/${{ steps.release.outputs.version }}/version.txt DongTai-agent-python.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-agent-java/${{ steps.release.outputs.version }}/version.txt DongTai-agent-java.version.txt || true
          ossutil cp oss://huoqi-public/iast/release-version/DongTai-agent-php/${{ steps.release.outputs.version }}/version.txt DongTai-agent-php.version.txt || true
          cat *.version.txt >> dist/version.txt
          cat dist/version.txt

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            dongtai/dongtai-web:${{ steps.release.outputs.version }}
            dongtai/dongtai-web:latest
            registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-web:${{ steps.release.outputs.version }}
            registry.cn-beijing.aliyuncs.com/huoxian_pub/dongtai-web:latest

      - name: finish build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：构建开始\n项目：${{github.repository}}\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'
